### ISSUE TITLE
Option for filtering yellow system articles

### ISSUE THREAD

**Issue by Charburner** [reneeb/opm-PrintSelectedArticles#1]
Hi Renee,

is it possible to add a sysconfig option to filter out article types?
For example, ignore by default all yellow articles which are generated by the system through (custom) ticket notifications.
That would be very helpful.

Thanks for any response!

**Comment by reneeb** [comment]
You could activate the sysconfig option Ticket::Frontend::TicketArticleFilter and then filter the articles... after activating the setting, there's the filter icon in the AgentTicketZoom just above the article list.

![image](https://github.com/reneeb/opm-PrintSelectedArticles/assets/144096/d8f33946-9b50-4a73-8352-aa9cf4bc2ab2)

**Comment by Charburner** [comment]
Thank you for your answer.
Perhaps I expressed it a little misleadingly. The filter option only has the function of restricting the view.
What I meant was a possibility to exclude all yellow articles of the type system from the print function or print formatting by default. Maybe by automatically pre selecting all print article checkboxes but the yellow ones?


![Unbenannt](https://github.com/reneeb/opm-PrintSelectedArticles/assets/26415550/14fe134f-fc1a-4172-b88a-978562ef687f)

**Comment by Charburner** [comment]
@reneeb Excuse my persistence, but I have to ask again whether the option that I hopefully described better in the last post is possible?
The background to this question is that ticket histories are to be printed as PDFs and stored in digital records. The possibly large number of yellow system type articles can be distracting to read. Manually removing the tick marks means also a lot of effort. Therefore I imagine an option or a workaround in the code that allows to generally exclude the yellow system articles when printing.
Would that be possible?

Thanks in advance
